Ensure use_ssl is set when using --disable-ssl.
Fixes linker failure:

```
Undefined symbols for architecture x86_64:
  "_use_ssl", referenced from:
      _process_arguments in nrpe-4fa9f6.o
      _handle_connection in nrpe-4fa9f6.o
      _read_packet in nrpe-4fa9f6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```